name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install NPM Dependencies
        run: npm install

      - name: Build Web Assets
        run: npm run build

      - name: Setup Java JDK
        uses: actions/setup-java@v5 # ارتقا به نسخه ۵ برای رفع اخطار
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build Android Release APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: android/app/build/outputs/apk/release/*.apk # استفاده از ستاره برای گرفتن هر نام فایلی که خروجی داده شود
